---
site_name: Inside the Fabric

theme:
  name: material

nav:
  - Home: index.md
  - Guides:
      - FortiGate-VM AWS Bootstrap: guides/fgvm_aws_bootstrap.md
      - FortiGate-VM Azure Bootstrap: guides/fgvm_az_bootstrap.md
      - FortiGate-VM GCP Bootstrap: guides/fgvm_gcp_bootstrap.md
  - Reference:
      - Policy and Objects:
          - Objects: reference/firewall_address.md
          - Policies: reference/firewall_policy.md

markdown_extensions:
  - admonition
  # Content Tabs
  - pymdownx.tabbed
  - pymdownx.superfences
  # collapsible Admonitions
  - pymdownx.details
  # insert external files
  - pymdownx.snippets
